[package]
name = "twilio"
version = "0.1.0-beta"
description = "Async hyper wrapper for Twilio API and TwiML generation"
repository = "https://github.com/leshow/twilio"
license = "MIT"
keywords = ["twilio", "twiml", "api", "async", "hyper"]
categories = ["network-programming", "api-bindings", "web-programming", "web-programming::http-client", "web-programming::http-server"]
authors = ["Evan Cameron <cameron.evan@gmail.com>"]

[dependencies]
hyper = "0.11"
hyper-tls = "0.1.3"
url = "1.7.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
xml-rs = "0.8"
futures = "0.1"
tokio-core = "0.1"