[package]
name = "twilio"
version = "0.1.0"
authors = ["Evan Cameron <cameron.evan@gmail.com>"]

[dependencies]
hyper = "0.11"
hyper-tls = "0.1.3"
url = "1.7.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
futures = "0.1"
tokio-core = "0.1"