[package]
name = "twilio-async"
version = "0.2.0"
description = """
An async and ergonomic wrapper around Twilio API & TwiML
"""
readme = "README.md"
repository = "https://github.com/leshow/twilio"
license = "MIT"
keywords = ["twilio", "twiml", "api", "async", "hyper"]
categories = ["network-programming", "api-bindings", "web-programming", "development-tools"]
authors = ["Evan Cameron <cameron.evan@gmail.com>"]
edition = "2018"

[dependencies]
hyper = "0.12"
hyper-tls = "0.3"
typed-headers = "0.1"
http = "0.1"
url = "1.7"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
xml-rs = "0.8"
futures = "0.1"
tokio-core = "0.1"

[workspace]
members = ["./", "twiml"]
